// automatically generated by the FlatBuffers compiler, do not modify

export enum StepMountingStatus {
  NONE = 0,
  WAITING_FOR_MOVEMENT = 1,
  WAITING_FOR_REST = 2,
  PROCESSING = 3,
  DONE = 4,
  ERROR_TIMEOUT = 5,
  ERROR_HIGH_ERROR = 6
}
