// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { StepMountingStatus } from '../../solarxr-protocol/rpc/step-mounting-status.js';


export class StepMountingStatusResponse implements flatbuffers.IUnpackableObject<StepMountingStatusResponseT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StepMountingStatusResponse {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStepMountingStatusResponse(bb:flatbuffers.ByteBuffer, obj?:StepMountingStatusResponse):StepMountingStatusResponse {
  return (obj || new StepMountingStatusResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStepMountingStatusResponse(bb:flatbuffers.ByteBuffer, obj?:StepMountingStatusResponse):StepMountingStatusResponse {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StepMountingStatusResponse()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

progress():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt8(this.bb_pos + offset) : 0;
}

status():StepMountingStatus {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.readUint8(this.bb_pos + offset) : StepMountingStatus.NONE;
}

static startStepMountingStatusResponse(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addProgress(builder:flatbuffers.Builder, progress:number) {
  builder.addFieldInt8(0, progress, 0);
}

static addStatus(builder:flatbuffers.Builder, status:StepMountingStatus) {
  builder.addFieldInt8(1, status, StepMountingStatus.NONE);
}

static endStepMountingStatusResponse(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createStepMountingStatusResponse(builder:flatbuffers.Builder, progress:number, status:StepMountingStatus):flatbuffers.Offset {
  StepMountingStatusResponse.startStepMountingStatusResponse(builder);
  StepMountingStatusResponse.addProgress(builder, progress);
  StepMountingStatusResponse.addStatus(builder, status);
  return StepMountingStatusResponse.endStepMountingStatusResponse(builder);
}

unpack(): StepMountingStatusResponseT {
  return new StepMountingStatusResponseT(
    this.progress(),
    this.status()
  );
}


unpackTo(_o: StepMountingStatusResponseT): void {
  _o.progress = this.progress();
  _o.status = this.status();
}
}

export class StepMountingStatusResponseT implements flatbuffers.IGeneratedObject {
constructor(
  public progress: number = 0,
  public status: StepMountingStatus = StepMountingStatus.NONE
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return StepMountingStatusResponse.createStepMountingStatusResponse(builder,
    this.progress,
    this.status
  );
}
}
