// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

@SuppressWarnings("unused")
public final class StepMountingStatusResponse extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_22_10_26(); }
  public static StepMountingStatusResponse getRootAsStepMountingStatusResponse(ByteBuffer _bb) { return getRootAsStepMountingStatusResponse(_bb, new StepMountingStatusResponse()); }
  public static StepMountingStatusResponse getRootAsStepMountingStatusResponse(ByteBuffer _bb, StepMountingStatusResponse obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public StepMountingStatusResponse __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte progress() { int o = __offset(4); return o != 0 ? bb.get(o + bb_pos) : 0; }
  public int status() { int o = __offset(6); return o != 0 ? bb.get(o + bb_pos) & 0xFF : 0; }

  public static int createStepMountingStatusResponse(FlatBufferBuilder builder,
      byte progress,
      int status) {
    builder.startTable(2);
    StepMountingStatusResponse.addStatus(builder, status);
    StepMountingStatusResponse.addProgress(builder, progress);
    return StepMountingStatusResponse.endStepMountingStatusResponse(builder);
  }

  public static void startStepMountingStatusResponse(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addProgress(FlatBufferBuilder builder, byte progress) { builder.addByte(0, progress, 0); }
  public static void addStatus(FlatBufferBuilder builder, int status) { builder.addByte(1, (byte) status, (byte) 0); }
  public static int endStepMountingStatusResponse(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public StepMountingStatusResponse get(int j) { return get(new StepMountingStatusResponse(), j); }
    public StepMountingStatusResponse get(StepMountingStatusResponse obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
  public StepMountingStatusResponseT unpack() {
    StepMountingStatusResponseT _o = new StepMountingStatusResponseT();
    unpackTo(_o);
    return _o;
  }
  public void unpackTo(StepMountingStatusResponseT _o) {
    byte _oProgress = progress();
    _o.setProgress(_oProgress);
    int _oStatus = status();
    _o.setStatus(_oStatus);
  }
  public static int pack(FlatBufferBuilder builder, StepMountingStatusResponseT _o) {
    if (_o == null) return 0;
    return createStepMountingStatusResponse(
      builder,
      _o.getProgress(),
      _o.getStatus());
  }
}

