// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

import java.nio.*;
import java.lang.*;
import java.util.*;
import com.google.flatbuffers.*;

public class StepMountingStatusResponseT {
  private byte progress;
  private int status;

  public byte getProgress() { return progress; }

  public void setProgress(byte progress) { this.progress = progress; }

  public int getStatus() { return status; }

  public void setStatus(int status) { this.status = status; }


  public StepMountingStatusResponseT() {
    this.progress = 0;
    this.status = 0;
  }
}

