// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc;

@SuppressWarnings("unused")
public final class StepMountingStatus {
  private StepMountingStatus() { }
  public static final int NONE = 0;
  public static final int WAITING_FOR_MOVEMENT = 1;
  public static final int WAITING_FOR_REST = 2;
  public static final int PROCESSING = 3;
  public static final int DONE = 4;
  public static final int ERROR_TIMEOUT = 5;
  public static final int ERROR_HIGH_ERROR = 6;

  public static final String[] names = { "NONE", "WAITING_FOR_MOVEMENT", "WAITING_FOR_REST", "PROCESSING", "DONE", "ERROR_TIMEOUT", "ERROR_HIGH_ERROR", };

  public static String name(int e) { return names[e]; }
}

