// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



export class ServerGuards implements flatbuffers.IUnpackableObject<ServerGuardsT> {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ServerGuards {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsServerGuards(bb:flatbuffers.ByteBuffer, obj?:ServerGuards):ServerGuards {
  return (obj || new ServerGuards()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsServerGuards(bb:flatbuffers.ByteBuffer, obj?:ServerGuards):ServerGuards {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ServerGuards()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

canDoMounting():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

canDoYawReset():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

canDoUserHeightCalibration():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

canDoStepMounting():boolean {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? !!this.bb!.readInt8(this.bb_pos + offset) : false;
}

static startServerGuards(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addCanDoMounting(builder:flatbuffers.Builder, canDoMounting:boolean) {
  builder.addFieldInt8(0, +canDoMounting, +false);
}

static addCanDoYawReset(builder:flatbuffers.Builder, canDoYawReset:boolean) {
  builder.addFieldInt8(1, +canDoYawReset, +false);
}

static addCanDoUserHeightCalibration(builder:flatbuffers.Builder, canDoUserHeightCalibration:boolean) {
  builder.addFieldInt8(2, +canDoUserHeightCalibration, +false);
}

static addCanDoStepMounting(builder:flatbuffers.Builder, canDoStepMounting:boolean) {
  builder.addFieldInt8(3, +canDoStepMounting, +false);
}

static endServerGuards(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createServerGuards(builder:flatbuffers.Builder, canDoMounting:boolean, canDoYawReset:boolean, canDoUserHeightCalibration:boolean, canDoStepMounting:boolean):flatbuffers.Offset {
  ServerGuards.startServerGuards(builder);
  ServerGuards.addCanDoMounting(builder, canDoMounting);
  ServerGuards.addCanDoYawReset(builder, canDoYawReset);
  ServerGuards.addCanDoUserHeightCalibration(builder, canDoUserHeightCalibration);
  ServerGuards.addCanDoStepMounting(builder, canDoStepMounting);
  return ServerGuards.endServerGuards(builder);
}

unpack(): ServerGuardsT {
  return new ServerGuardsT(
    this.canDoMounting(),
    this.canDoYawReset(),
    this.canDoUserHeightCalibration(),
    this.canDoStepMounting()
  );
}


unpackTo(_o: ServerGuardsT): void {
  _o.canDoMounting = this.canDoMounting();
  _o.canDoYawReset = this.canDoYawReset();
  _o.canDoUserHeightCalibration = this.canDoUserHeightCalibration();
  _o.canDoStepMounting = this.canDoStepMounting();
}
}

export class ServerGuardsT implements flatbuffers.IGeneratedObject {
constructor(
  public canDoMounting: boolean = false,
  public canDoYawReset: boolean = false,
  public canDoUserHeightCalibration: boolean = false,
  public canDoStepMounting: boolean = false
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return ServerGuards.createServerGuards(builder,
    this.canDoMounting,
    this.canDoYawReset,
    this.canDoUserHeightCalibration,
    this.canDoStepMounting
  );
}
}
