// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

import java.nio.*
import kotlin.math.sign
import com.google.flatbuffers.*

@Suppress("unused")
class StepMountingStatusResponse : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : StepMountingStatusResponse {
        __init(_i, _bb)
        return this
    }
    val progress : Byte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    val status : UByte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    companion object {
        @JvmStatic
        fun validateVersion() = Constants.FLATBUFFERS_22_10_26()
        @JvmStatic
        fun getRootAsStepMountingStatusResponse(_bb: ByteBuffer): StepMountingStatusResponse = getRootAsStepMountingStatusResponse(_bb, StepMountingStatusResponse())
        @JvmStatic
        fun getRootAsStepMountingStatusResponse(_bb: ByteBuffer, obj: StepMountingStatusResponse): StepMountingStatusResponse {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        @JvmStatic
        fun createStepMountingStatusResponse(builder: FlatBufferBuilder, progress: Byte, status: UByte) : Int {
            builder.startTable(2)
            addStatus(builder, status)
            addProgress(builder, progress)
            return endStepMountingStatusResponse(builder)
        }
        @JvmStatic
        fun startStepMountingStatusResponse(builder: FlatBufferBuilder) = builder.startTable(2)
        @JvmStatic
        fun addProgress(builder: FlatBufferBuilder, progress: Byte) = builder.addByte(0, progress, 0)
        @JvmStatic
        fun addStatus(builder: FlatBufferBuilder, status: UByte) = builder.addByte(1, status.toByte(), 0)
        @JvmStatic
        fun endStepMountingStatusResponse(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
