// automatically generated by the FlatBuffers compiler, do not modify

package solarxr_protocol.rpc

@Suppress("unused")
class StepMountingStatus private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val WAITINGFORMOVEMENT: UByte = 1u
        const val WAITINGFORREST: UByte = 2u
        const val PROCESSING: UByte = 3u
        const val DONE: UByte = 4u
        const val ERRORTIMEOUT: UByte = 5u
        const val ERRORHIGHERROR: UByte = 6u
        val names : Array<String> = arrayOf("NONE", "WAITING_FOR_MOVEMENT", "WAITING_FOR_REST", "PROCESSING", "DONE", "ERROR_TIMEOUT", "ERROR_HIGH_ERROR")
        @JvmStatic
        fun name(e: Int) : String = names[e]
    }
}
